package config

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Config holds all runtime settings for AgentRoom.
type Config struct {
	Port      string
	Bind      string
	DB        string
	BaseURL   string
	AdminName string
	Lang      string

	// Path where this config was loaded from.
	FilePath string
}

// Defaults returns a Config populated with default values.
func Defaults() Config {
	dataDir := defaultDataDir()
	return Config{
		Port:      "8080",
		Bind:      "0.0.0.0",
		DB:        filepath.Join(dataDir, "agentroom.db"),
		BaseURL:   "",
		AdminName: "admin",
		Lang:      "en",
		FilePath:  defaultConfigPath(),
	}
}

// Load reads a config file and returns a Config.
// Missing keys fall back to defaults.
func Load(path string) (Config, error) {
	cfg := Defaults()
	cfg.FilePath = path

	f, err := os.Open(path)
	if os.IsNotExist(err) {
		return cfg, nil
	}
	if err != nil {
		return cfg, err
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		k = strings.TrimSpace(k)
		v = strings.TrimSpace(v)
		// strip optional surrounding quotes
		if len(v) >= 2 && ((v[0] == '"' && v[len(v)-1] == '"') || (v[0] == '\'' && v[len(v)-1] == '\'')) {
			v = v[1 : len(v)-1]
		}
		switch k {
		case "AGENTROOM_PORT":
			cfg.Port = v
		case "AGENTROOM_BIND":
			cfg.Bind = v
		case "AGENTROOM_DB":
			cfg.DB = v
		case "AGENTROOM_BASE_URL":
			cfg.BaseURL = v
		case "AGENTROOM_ADMIN_AGENT_NAME":
			cfg.AdminName = v
		case "AGENTROOM_LANG":
			cfg.Lang = v
		}
	}
	return cfg, scanner.Err()
}

// Save writes the config to its FilePath.
func Save(cfg Config) error {
	dir := filepath.Dir(cfg.FilePath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}

	f, err := os.OpenFile(cfg.FilePath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0600)
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintln(f, "# AgentRoom configuration")
	fmt.Fprintln(f, "# Generated by: agentroom init")
	fmt.Fprintln(f, "# Re-run the setup wizard at any time with: agentroom init")
	fmt.Fprintln(f)
	fmt.Fprintf(f, "AGENTROOM_PORT=%s\n", cfg.Port)
	fmt.Fprintf(f, "AGENTROOM_BIND=%s\n", cfg.Bind)
	fmt.Fprintf(f, "AGENTROOM_DB=%s\n", cfg.DB)
	fmt.Fprintf(f, "AGENTROOM_BASE_URL=%s\n", cfg.BaseURL)
	fmt.Fprintf(f, "AGENTROOM_ADMIN_AGENT_NAME=%s\n", cfg.AdminName)
	fmt.Fprintf(f, "AGENTROOM_LANG=%s\n", cfg.Lang)
	return nil
}

// LoadFromEnv applies environment variable overrides on top of cfg.
func LoadFromEnv(cfg *Config) {
	if v := os.Getenv("AGENTROOM_PORT"); v != "" {
		cfg.Port = v
	}
	if v := os.Getenv("AGENTROOM_BIND"); v != "" {
		cfg.Bind = v
	}
	if v := os.Getenv("AGENTROOM_DB"); v != "" {
		cfg.DB = v
	}
	if v := os.Getenv("AGENTROOM_BASE_URL"); v != "" {
		cfg.BaseURL = v
	}
	if v := os.Getenv("AGENTROOM_ADMIN_AGENT_NAME"); v != "" {
		cfg.AdminName = v
	}
	if v := os.Getenv("AGENTROOM_LANG"); v != "" {
		cfg.Lang = v
	}
}

// DefaultConfigPath returns the default config file path.
func DefaultConfigPath() string { return defaultConfigPath() }

func defaultConfigPath() string {
	if os.Getuid() == 0 {
		return "/etc/agentroom/agentroom.conf"
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".agentroom", "agentroom.conf")
}

func defaultDataDir() string {
	if os.Getuid() == 0 {
		return "/var/lib/agentroom"
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".agentroom")
}
